const LANG_DATA = {
    'zh': {
        title: 'ContextCarry',
        status_ready: '準備就緒',
        status_scanning: '正在掃描...',
        label_prefix: '自訂前綴提示詞:',
        placeholder: '在此輸入要給 AI 的前導指令...',
        btn_scan: '重新掃描頁面',
        btn_scan_done: '已重新掃描',
        btn_select_all: '全選所有訊息',
        btn_unselect_all: '取消全選',
        btn_dl: '輸出籃子',
        btn_copy: '複製到剪貼簿',
        label_transfer: '轉移並開啟 (Cross-LLM):',
        msg_detected: '偵測到 {n} 則訊息',
        msg_selected: '已選取: {n} 則',
        alert_no_selection: '請先選取對話或加入採集籃！',
        alert_copy_done: '內容已複製！',
        alert_fail: '操作失敗，請檢查權限',
        btn_add_title: '加入此段落 (Shift 可連選)',
        toast_autofill: 'Context-Carry: 已自動填入內容.',
        default_prompt: `請針對以下內容進行總結，列出重點摘要與結論：`,
        label_basket: '🧺 跨視窗採集籃 (Basket):',
        btn_add_basket: '加入 (+)',
        btn_clear_basket: '清空',
        btn_paste_basket: '填入此視窗',
        basket_status: '目前有 {n} 筆資料 (點擊預覽 ▼)',
        basket_status_empty: '採集籃是空的',
        toast_basket_add: '已加入採集籃 🧺',
        toast_basket_clear: '採集籃已清空 🗑️',
        preview_del_tooltip: '刪除此筆資料',
        preview_drag_hint: '可拖曳排序 ⇅ (懸停可看詳情)',
        token_est: '📊 預估 Token:',
        token_warn_title: '⚠️ Token 數量警告',
        token_warn_msg: '預估內容 ({est}) 超過了 {platform} 的建議限制 ({limit})。\n\n強行轉移可能會導致記憶遺失。\n是否仍要繼續？',
        btn_paint: '🖌️ 圈選',
        paint_tooltip: '圈選畫面區域文字',
        toast_enter_paint: '進入圈選模式 (按 ESC 退出)',
        paint_no_text: '未選取到任何文字',
        preview_title: '📝 <b>確認擷取內容 (Preview)</b>',
        preview_words: '字數',
        preview_cancel: '取消',
        preview_confirm: '加入採集籃',
        source_area_select: ' (圈選)',
        alert_llm_only: '自動填入功能 (Auto-fill) 僅支援(ChatGPT, Claude, Gemini, Grok)',
        btn_summary: 'AI 總結',
        btn_new_doc: '建立筆記',
        enter_new_doc: '請輸入內容：',
        ai_settings_title: 'AI 設定',
        ai_settings_endpoint: 'API 網址 (Endpoint)',
        ai_settings_api_key: 'API 金鑰 (Key)',
        ai_settings_save: '儲存設定',
        ai_unconfigured: '尚未設定 AI，請先進行設定。',
        ai_response_title: 'AI 回應',
        ai_response_tab_response: '回應',
        ai_response_tab_context: '上下文',
        ai_summary_sending: 'AI 正在總結中...',
        ai_summary_error: 'AI 請求失敗',
        drawer_toggle: '進階選項 & 採集籃',
        ai_setting_tab: 'AI 設定',
        ai_response_tab: 'AI 回應',
        ai_config_title: 'AI 設定',
        ai_provider: '模型供應商 (Provider)',
        ai_api_key: 'API 金鑰 (Key)',
        ai_model: '模型名稱 (Model)',
        ai_endpoint_toggle: 'API 網址 (Endpoint)',
        ai_save: '儲存設定',
        ai_modal_title: 'AI 回應',
        ai_modal_processing: 'AI 思考中...',
        ai_modal_done: '✅ 完成',
        ai_tab_res: 'AI 回應',
        ai_tab_ctx: '發送內容 (編輯)',
        btn_resend: '🔄 更新內容並重試',
        btn_save_file: '⬇️ 存為檔案',
        btn_paste: '📋 填入目前視窗',
        btn_send_all: '🚀 貼到全部',
        btn_copy_res: '複製',
        btn_clear_res: '清空',
        btn_min_restore: '還原視窗',
        btn_lang_title: '切換語言',
        btn_theme_title: '切換深色模式',
        btn_close_title: '關閉面板',
        hint_shortcut_lang: ' (Alt+L)',
        hint_shortcut_paint: ' (Alt+C)',
        hint_shortcut_toggle: ' (Alt+M)',
        btn_switch_ui: '切換介面風格',
        hatch_expand: '▼ 展開貨艙',
        hatch_retract: '▲ 收起貨艙',
        btn_quick_settings: '⚙️ AI 設定',
        unlock_title: '🔒 啟用 AI 功能',
        unlock_warning: `⚠️ <b>重要：AI功能採用「自備金鑰-BYO Key」模式。</b>
<br/><br/>
<ul>
    <li><b>金鑰由您控制：</b>您提供的API 金鑰<b>僅儲存在您瀏覽器的本地儲存空間</b>中。</li><br/><br/>
    <li><b>數據保持本地：</b>所有內容<b>絕不會被傳輸到 Context-Carry 開發者的任何伺服器</b>。所有 AI 請求都是從您的瀏覽器直接發送到您選擇的第三方 LLM 供應商。</li><br/><br/>
    <li><b>費用由您承擔：</b>這些 LLM 服務<b>不是免費的</b>，將根據您的金鑰和使用量向您的帳戶收取費用。</li>
</ul>
<br/>
啟用此功能，即表示您<b>完全知情</b>並同意使用您自己的金鑰，並由您自行承擔所有第三方服務費用。`,
        unlock_cancel: '取消',
        unlock_confirm: '我了解，啟用 AI',
        unlock_enabling: '啟用中...',
        unlock_toast_success: 'AI 功能已啟用 🔓',
        ai_panel_active: '啟用面板 {n}',
        ai_panel_empty_title: '等待輸入',
        ai_panel_empty_msg: '<span id="goto-edit-{n}" style="color:#00d2ff; cursor:pointer; text-decoration:underline;">編輯</span> 加入內容',
        ai_panel_status_ready: '就緒。點擊 🚀 開始。',
        ai_panel_copy_tooltip: '複製回應',
        ai_panel_close_tooltip: '停用面板',
        ai_panel_not_activated: '面板 {n} 未啟用',
        ai_import_basket_tooltip: '匯入採集籃內容',
        ai_copy_ctx_tooltip: '複製此內容',
        ai_ctx_placeholder: '在此輸入上下文...',
        ai_save_indicator_saving: '儲存中...',
        ai_save_indicator_saved: '已儲存 ✓',
        label_load_profile: '讀取設定檔',
        label_config_name: '設定名稱 (Alias)',
        label_ai_provider: '模型供應商 (Provider)',
        label_api_key: 'API 金鑰 (Key)',
        label_target_model: '目標模型 (Model)',
        label_endpoint: 'API 網址 (Endpoint)',
        option_new_profile: '-- 建立新設定 --',
        option_loading: '載入中...',
        btn_align: '🔁 同步全部',
        btn_align_tooltip: '將面板 {n} 的內容複製到「所有」面板',
        msg_align_confirm: '確定要將面板 {n} 的內容複製覆蓋到其他所有面板嗎？',
        btn_apply_view: '套用並檢視 >>',
        btn_start_all: '⚡ 全部開始',
        btn_copy_all_res: '📋 複製全部',
        warn_resource_title: '⚠️ 資源消耗警告',
        warn_resource_msg1: '即將啟用多節點視窗 (Multi-Node View)。',
        warn_resource_msg2: '這將最多同時發送 3 個 AI 請求。',
        warn_resource_msg3: '請確認所有面板皆已設定 API Key，以免產生意外費用或錯誤。',
        btn_proceed: '繼續執行',
        btn_abort: '取消',
        msg_no_ready_panels: '沒有準備就緒的面板 (請檢查內容或設定)',
        msg_all_copied: '已複製所有回應！',
        msg_context_synced: '上下文已同步',
        msg_imported_basket: '已匯入 {n} 筆資料至面板 {i}',
        msg_basket_empty: '採集籃是空的！',
        ph_config_name: '例如: 工作用',
        ph_api_key: 'sk-...',
        ph_model: '例如: gpt-4o-mini',
        ai_panel_resend: '開始 / 重試',
        btn_layout_single: '單頁模式',
        btn_layout_quad: '多頁模式',
        mech_header: '// 神經網路連線設定',
        mech_sub: '多重金鑰系統',
        mech_hide_ep: '[ 通道網址 ]',
        mech_edit_ep: '[ 編輯網址 ]',
        btn_export_json: '匯出設定檔 (JSON)',
        btn_import_json: '匯入設定檔 (JSON)',
        msg_import_success: '設定匯入成功',
        msg_import_fail: '匯入失敗：格式錯誤或是無效的 JSON 檔',
        prompt_sep_basket: '\n========== [ 採集籃內容 ] ==========\n',
        prompt_item_prefix: '[第 {n} 筆資料 來源: {source}]',
        prompt_end: '\n[上下文結束]',
        prompt_fragment: '--- 對話片段 ---',
        src_manual: '手動輸入 (新筆記)',
        src_drop: ' (拖曳內容)',
        src_file: ' (檔案匯入)',
        src_local: ' (本機檔案)',
        tooltip_transfer_to: '轉移上下文至 {name}',
        tooltip_send_to: '發送此回應到 {name}',
        tooltip_send_all_to: '將所有面板回應發送到 {name}',
        overlay_drop_add: '放開以加入採集籃',
        overlay_acquiring: '數據擷取中...',
        sys_btn_summary: '📝',
        sys_tooltip_summary: '載入: 重點總結',
        sys_prompt_summary: '請針對以下內容進行總結，列出重點摘要與結論：',
        sys_btn_translate: '🌐',
        sys_tooltip_translate: '載入: 翻譯成繁中',
        sys_prompt_translate: '請將以下內容翻譯成流暢、專業的繁體中文：',
        sys_btn_explain: '💡',
        sys_tooltip_explain: '載入: 白話解釋',
        sys_prompt_explain: '請用簡單易懂的方式解釋以下內容：',
        sys_btn_custom_add: '➕',
        sys_btn_custom_user: '👤',
        sys_tooltip_custom_empty: '儲存目前 Prompt 為自訂模板',
        sys_tooltip_custom_saved: '左鍵: 載入自訂模板\nShift+左鍵: 覆蓋儲存目前內容',
        toast_custom_saved: '自訂 Prompt 已儲存 ✨',
        sys_btn_save: '💾',
        sys_tooltip_save: '儲存/管理 自訂 Prompt (最多3組)',
        sys_tooltip_load: '載入自訂 Prompt',
        prompt_save_title: '儲存自訂 Prompt',
        prompt_save_name_ph: '輸入名稱 (例如: 翻譯助手)',
        prompt_save_btn_new: '新增儲存',
        prompt_save_btn_overwrite: '覆蓋選取項目',
        prompt_save_limit: '已達上限 (3組)，請選擇項目進行覆蓋',
        prompt_load_empty: '尚未儲存任何 Prompt',
        prompt_toast_saved: 'Prompt 已儲存 ✨',
        drone_title: '拖曳文字至此儲存 / 點擊開啟 Context-Carry',
        drone_dismiss: '在此網站隱藏 (直到點擊擴充功能圖示)',
        mm_title_single: '🤖 AI 回應',
        mm_title_multi: '⚡ 工作流引擎 (Workflow)',
        mm_view_multi: '🔀 切換多節點視圖',
        mm_view_single: '⏹ 切換單一視圖',
        mm_loop_label: '迴圈:',
        mm_add_node: '+ 節點',
        mm_run: '▶ 執行',
        mm_stop: '⏹ 中止',
        mm_basket: '🧺 採集籃',
        mm_basket_paste: '📥 貼至所有節點',
        mm_basket_export: '⬇️ 匯出籃子',
        mm_basket_import: '⬆️ 匯入籃子',
        mm_send_all: '🚀 貼到所有平台',
        mm_basket_tip_drop: '放開以加入採集籃',
        mm_basket_added: '已加入採集籃',
        mm_basket_empty: '採集籃是空的',
        mm_basket_paste_all: '📥 貼至所有節點',
        mm_node_edit: '編輯',
        mm_node_clear: '清空',
        mm_node_copy: '複製',
        mm_node_drag: '拖曳內容',
        mm_node_run: '執行此節點',
        mm_save_txt: '存為 .txt',
        mm_save_md: '存為 .md',
        mm_confirm_del_conn: '刪除連線?',
        mm_confirm_clear: '確定清空內容?',
        pip_tab_collect: '📥 收集箱',
        pip_tab_flow: '⚡ 工作流',
        pip_drop_title: '放開以匯入',
        pip_drop_sub: '(支援檔案、文字、程式碼)',
        pip_tooltip_theme: '切換主題',
        pip_tooltip_settings: '設定',
        pip_tooltip_max: '最大化/還原',
        pip_btn_paste: '貼上',
        pip_btn_export: '匯出',
        pip_btn_clear: '清空',
        pip_empty_list: '目前沒有資料',
        pip_basket_title: '🧺 採集籃',
        pip_basket_empty: '空空如也',
        pip_tag_all: '全部',
        pip_node_idle: '閒置',
        pip_node_running: '執行中',
        pip_node_done: '完成',
        pip_node_error: '錯誤',
        pip_node_ph: '等待輸入...',
        pip_node_no_config: '無設定',
        pip_tooltip_run_node: '執行此節點',
        pip_tooltip_edit_node: '編輯內容',
        pip_tooltip_del_node: '刪除節點',
        pip_modal_clear_title: '清空採集籃',
        pip_modal_clear_msg: '確定要刪除所有項目嗎？此動作無法復原。',
        pip_modal_confirm: '確認清空',
        pip_modal_cancel: '取消',
        pip_export_title: '匯出採集籃',
        pip_label_filename: '檔案名稱',
        pip_label_format: '匯出格式',
        pip_btn_save_export: '匯出 / 儲存',
        pip_toast_pasted: '已從剪貼簿貼上 ✨',
        pip_toast_empty: '剪貼簿是空的',
        pip_toast_perm: '需要權限 (請先點擊視窗內部)',
        pip_toast_cleared: '採集籃已清空 🗑️',
        pip_confirm_del_item: '刪除',
        robot_comms_tab: '通訊',
        drone_cargo: '收集',
        hint_drag: ' (拖曳)',
        toast_input_not_found: '未偵測到輸入框，內容已複製到剪貼簿 📋',
        toast_file_too_large: '❌ 檔案太大: {name} ({size}MB). 上限 10MB.',
        toast_file_loaded: '檔案已載入: {name}',
        toast_manual_add_source: '手動輸入'
    },
    'en': {
        title: 'ContextCarry',
        status_ready: 'Ready',
        status_scanning: 'Scanning...',
        label_prefix: '[System Prompt]:',
        placeholder: 'Enter instructions for the AI here...',
        btn_scan: 'Rescan Page',
        btn_select_all: 'Select All',
        btn_unselect_all: 'Unselect All',
        btn_scan_done: 'Scanned',
        btn_dl: 'Export Basket',
        btn_copy: 'Copy to Clipboard',
        label_transfer: 'Transfer to (Cross-LLM):',
        msg_detected: 'Detected {n} messages',
        msg_selected: 'Selected: {n}',
        alert_no_selection: 'Please select messages or add to basket first!',
        alert_copy_done: 'Content copied!',
        alert_fail: 'Operation failed. Check permissions.',
        btn_add_title: 'Add this block (Shift for range)',
        toast_autofill: 'Context-Carry: Content Auto-filled.',
        default_prompt: `Please summarize the following content, highlighting key points and conclusions:`,
        label_basket: '🧺 Context Basket:',
        btn_add_basket: 'Add (+)',
        btn_clear_basket: 'Clear',
        btn_paste_basket: 'Paste Here',
        basket_status: '{n} items in basket (Click to View ▼)',
        basket_status_empty: 'Basket is empty',
        toast_basket_add: 'Added to Basket 🧺',
        toast_basket_clear: 'Basket Cleared 🗑️',
        preview_del_tooltip: 'Remove item',
        preview_drag_hint: 'Drag to reorder ⇅ (Hover for details)',
        token_est: '📊 Est. Tokens:',
        token_warn_title: '⚠️ Token Limit Warning',
        token_warn_msg: 'Content ({est}) exceeds recommended limit for {platform} ({limit}).\n\nTransferring may cause memory loss.\nDo you want to proceed?',
        btn_paint: '🖌️ Select',
        paint_tooltip: 'Select area of text',
        toast_enter_paint: 'Entered selection mode (Press ESC to exit)',
        paint_no_text: 'No text selected',
        preview_title: '📝 <b>Confirm selection (Preview)</b>',
        preview_words: 'Chars',
        preview_cancel: 'Cancel',
        preview_confirm: 'Add to Basket',
        source_area_select: ' (Area Select)',
        alert_llm_only: 'Auto-fill is only available on supported(ChatGPT, Claude, Gemini, Grok)',
        btn_summary: 'AI Summary',
        btn_new_doc: 'New Doc',
        enter_new_doc: 'Enter content',
        ai_settings_title: 'AI Settings',
        ai_settings_endpoint: 'API Endpoint',
        ai_settings_api_key: 'API Key',
        ai_settings_save: 'Save Settings',
        ai_unconfigured: 'AI is not configured yet. Please set it up.',
        ai_response_title: 'AI Response',
        ai_response_tab_response: 'Response',
        ai_response_tab_context: 'Context',
        ai_summary_sending: 'Summarizing...',
        ai_summary_error: 'Summarization failed',
        drawer_toggle: 'Advanced & Basket',
        ai_setting_tab: 'AI Settings',
        ai_response_tab: 'AI Response',
        ai_config_title: 'AI Configuration',
        ai_provider: 'Provider',
        ai_api_key: 'API Key',
        ai_model: 'Model Name',
        ai_endpoint_toggle: 'Advanced Endpoint',
        ai_save: 'Save Settings',
        ai_modal_title: 'AI Response',
        ai_modal_processing: 'AI Processing...',
        ai_modal_done: '✅ AI Done',
        ai_tab_res: 'Response',
        ai_tab_ctx: 'Sent Context (Edit)',
        btn_resend: '🔄 Re-send with edited context',
        btn_save_file: '⬇️ Save',
        btn_paste: '📋 Paste to Window',
        btn_send_all: '🚀 Paste to All',
        btn_copy_res: 'Copy',
        btn_clear_res: 'Clear',
        btn_min_restore: 'Restore',
        btn_lang_title: 'Switch Language',
        btn_theme_title: 'Toggle Dark Mode',
        btn_close_title: 'Close Panel',
        hint_shortcut_lang: ' (Alt+L)',
        hint_shortcut_paint: ' (Alt+C)',
        hint_shortcut_toggle: ' (Alt+M)',
        btn_switch_ui: 'Switch UI Style',
        hatch_expand: '▼ DEPLOY BASKET',
        hatch_retract: '▲ RETRACT BASKET',
        btn_quick_settings: '⚙️ AI Settings',
        unlock_title: '🔒 ENABLE AI FEATURES',
        unlock_warning: `⚠️ <b>IMPORTANT: AI Features operate under a "Bring Your Own Key" (BYO Key) model.</b>
<br/><br/>
<ul>
    <li><b>Key Control:</b> Your provided API keys are <b>stored exclusively in your browser's local storage</b>.</li><br/><br/>
    <li><b>Data Privacy:</b> All context content <b>is NEVER transmitted to any servers belonging to Context-Carry's developers</b>. All AI requests are sent directly from your browser to the third-party LLM provider you select.</li><br/><br/>
    <li><b>User Costs:</b> These LLM services are <b>NOT FREE</b> and will charge your account based on your usage.</li>
</ul>
<br/>
By enabling this feature, you <b>fully acknowledge</b> and agree to use your own keys, assuming all associated costs and liabilities with the third-party service.`,
        unlock_cancel: 'CANCEL',
        unlock_confirm: 'I UNDERSTAND, ENABLE AI',
        unlock_enabling: 'ENABLING...',
        unlock_toast_success: 'AI Features Enabled 🔓',
        ai_panel_active: 'ACTIVATE PANEL {n}',
        ai_panel_empty_title: 'Waiting for Input',
        ai_panel_empty_msg: 'Please add content in the <span id="goto-edit-{n}" style="color:#00d2ff; cursor:pointer; text-decoration:underline;">Edit Tab</span>',
        ai_panel_status_ready: 'Ready. Click 🚀 to start.',
        ai_panel_copy_tooltip: 'Copy Response',
        ai_panel_close_tooltip: 'Deactivate Panel',
        ai_panel_not_activated: 'PANEL {n} NOT ACTIVATED',
        ai_import_basket_tooltip: 'Import Basket Content',
        ai_copy_ctx_tooltip: 'Copy this context',
        ai_ctx_placeholder: 'Enter context here...',
        ai_save_indicator_saving: 'Saving...',
        ai_save_indicator_saved: 'Saved ✓',
        label_load_profile: 'LOAD PROFILE',
        label_config_name: 'CONFIG NAME',
        label_ai_provider: 'AI PROVIDER',
        label_api_key: 'API KEY',
        label_target_model: 'TARGET MODEL',
        label_endpoint: 'API ENDPOINT',
        option_new_profile: '-- Create New --',
        option_loading: 'Loading...',
        btn_align: '🔁 Align All',
        btn_align_tooltip: 'Copy context from Panel {n} to ALL panels',
        msg_align_confirm: 'Copy context from Panel {n} to all other panels?',
        btn_apply_view: 'Apply & View >>',
        btn_start_all: '⚡ Start All',
        btn_copy_all_res: '📋 Copy All',
        warn_resource_title: '⚠️ RESOURCE WARNING',
        warn_resource_msg1: 'Activating Multi-Node View (10 Nodes).',
        warn_resource_msg2: 'This launches 3 simultaneous AI requests.',
        warn_resource_msg3: 'Ensure you have set API keys for all panels.',
        btn_proceed: 'PROCEED',
        btn_abort: 'ABORT',
        msg_no_ready_panels: 'No ready panels (Check content/settings)',
        msg_all_copied: 'All responses copied!',
        msg_context_synced: 'Context synced',
        msg_imported_basket: 'Imported {n} items to Panel {i}',
        msg_basket_empty: 'Basket is empty!',
        ph_config_name: 'e.g. My GPT-4 Work',
        ph_api_key: 'sk-...',
        ph_model: 'e.g. gpt-4o-mini',
        ai_panel_resend: 'Start / Resend',
        btn_layout_single: 'Single View',
        btn_layout_quad: 'Quad View',
        mech_header: '// NEURAL UPLINK CONFIG',
        mech_sub: 'MULTI-KEY SYSTEM',
        mech_hide_ep: '[ HIDE ENDPOINT ]',
        mech_edit_ep: '[ EDIT ENDPOINT ]',
        btn_export_json: 'Export Config (JSON)',
        btn_import_json: 'Import Config (JSON)',
        msg_import_success: 'Configuration imported successfully',
        msg_import_fail: 'Import failed: Invalid format or JSON',
        prompt_sep_basket: '\n========== [ BASKET CONTENT ] ==========\n',
        prompt_item_prefix: '[Basket Item {n} from {source}]',
        prompt_end: '\n[END OF CONTEXT]',
        prompt_fragment: '--- Fragment ---',
        src_manual: 'Manual Entry (New Doc)',
        src_drop: ' (Drag & Drop)',
        src_file: ' (File)',
        src_local: ' (Local File)',
        tooltip_transfer_to: 'Transfer Context to {name}',
        tooltip_send_to: 'Send this response to {name}',
        tooltip_send_all_to: 'Send all responses to {name}',
        overlay_drop_add: 'Drop to Add to Basket',
        overlay_acquiring: 'ACQUIRING DATA...',
        sys_btn_summary: '📝',
        sys_tooltip_summary: 'Load: Summary',
        sys_prompt_summary: 'Please summarize the following content, highlighting key points and conclusions:',
        sys_btn_translate: '🌐',
        sys_tooltip_translate: 'Load: Translate',
        sys_prompt_translate: 'Please translate the following content into professional English:',
        sys_btn_explain: '💡',
        sys_tooltip_explain: 'Load: Explain',
        sys_prompt_explain: 'Please explain the following content in simple terms:',
        sys_btn_custom_add: '➕',
        sys_btn_custom_user: '👤',
        sys_tooltip_custom_empty: 'Save current prompt as custom',
        sys_tooltip_custom_saved: 'Click: Load Custom\nShift+Click: Overwrite Save',
        toast_custom_saved: 'Custom Prompt Saved ✨',
        sys_btn_save: '💾',
        sys_tooltip_save: 'Save/Manage Custom Prompts (Max 3)',
        sys_tooltip_load: 'Load Custom Prompt',
        prompt_save_title: 'Save Custom Prompt',
        prompt_save_name_ph: 'Enter Name (e.g. My Helper)',
        prompt_save_btn_new: 'Save as New',
        prompt_save_btn_overwrite: 'Overwrite Selected',
        prompt_save_limit: 'Limit Reached (3), please overwrite.',
        prompt_load_empty: 'No saved prompts',
        prompt_toast_saved: 'Prompt Saved ✨',
        drone_title: 'Drag text here to save / Click to open Context-Carry',
        drone_dismiss: 'Don\'t show on this site until I click the extension icon',
        mm_title_single: '🤖 AI Response',
        mm_title_multi: '⚡ Workflow Engine',
        mm_view_multi: '🔀 Multi-Node View',
        mm_view_single: '⏹ Single View',
        mm_loop_label: 'Loop:',
        mm_add_node: '+ Node',
        mm_run: '▶ Run',
        mm_stop: '⏹ ABORT',
        mm_basket: '🧺 Basket',
        mm_basket_paste: '📥 Paste to All',
        mm_basket_export: '⬇️ Export Basket',
        mm_basket_import: '⬆️ Import Basket',
        mm_send_all: '🚀 NewTab to All',
        mm_basket_tip_drop: 'Drop to Add',
        mm_basket_added: 'Added to Basket',
        mm_basket_empty: 'Basket is empty',
        mm_basket_paste_all: '📥 Paste to All',
        mm_node_edit: 'Edit',
        mm_node_clear: 'Clear',
        mm_node_copy: 'Copy',
        mm_node_drag: 'Drag Content',
        mm_node_run: 'Run Node',
        mm_save_txt: 'Save .txt',
        mm_save_md: 'Save .md',
        mm_confirm_del_conn: 'Delete connection?',
        mm_confirm_clear: 'Clear content?',
        pip_tab_collect: '📥 COLLECTOR',
        pip_tab_flow: '⚡ WORKFLOW',
        pip_drop_title: 'DROP TO IMPORT',
        pip_drop_sub: '(Files, Text, Code)',
        pip_tooltip_theme: 'Toggle Theme',
        pip_tooltip_settings: 'Settings',
        pip_tooltip_max: 'Maximize/Restore',
        pip_btn_paste: 'Paste',
        pip_btn_export: 'Export',
        pip_btn_clear: 'Clear',
        pip_empty_list: 'No items found.',
        pip_basket_title: '🧺 BASKET',
        pip_basket_empty: 'Empty',
        pip_tag_all: 'All',
        pip_node_idle: 'IDLE',
        pip_node_running: 'RUNNING',
        pip_node_done: 'DONE',
        pip_node_error: 'ERROR',
        pip_node_ph: 'Waiting for input...',
        pip_node_no_config: 'No Config',
        pip_tooltip_run_node: 'Run Node',
        pip_tooltip_edit_node: 'Edit Content',
        pip_tooltip_del_node: 'Delete Node',
        pip_modal_clear_title: 'Clear Basket',
        pip_modal_clear_msg: 'Are you sure you want to remove all items? This action cannot be undone.',
        pip_modal_confirm: 'Confirm',
        pip_modal_cancel: 'Cancel',
        pip_export_title: 'EXPORT BASKET',
        pip_label_filename: 'FILE NAME',
        pip_label_format: 'FORMAT',
        pip_btn_save_export: 'EXPORT / SAVE',
        pip_toast_pasted: 'Pasted from Clipboard ✨',
        pip_toast_empty: 'Clipboard is empty',
        pip_toast_perm: 'Permission required (Click window first)',
        pip_toast_cleared: 'Basket Cleared 🗑️',
        pip_confirm_del_item: 'Delete',
        robot_comms_tab: 'COMMS',
        drone_cargo: 'Cargo',
        hint_drag: ' (Drag)',
        toast_input_not_found: 'No input field detected. Copied to clipboard 📋',
        toast_file_too_large: '❌ File too large: {name} ({size}MB). Max 10MB.',
        toast_file_loaded: 'File loaded: {name}',
        toast_manual_add_source: 'Manual Entry'
    }
};